# before_script:
#   - echo "Before script"
#   - cd /var/www/html/easy-store
before_script:
  # Git and SSH setup to clone private repos
  # Needs the deploykey file to be installed in all dependent repositories
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  # Add gitlab to known_hosts
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
  # Start the ssh agent and add the deploykey
  # - chmod 400 deploykey
  # - eval $(ssh-agent -s)
  # - ssh-add deploykey
building:
  stage: build
  script:
    - echo "Build Stage"
    - whoami
    - git clone git@gitlab.com:999itsolution/easy-store.git
    # - git reset --hard
    # - git pull --ff-only
    # - php artisan cache:clear
    # - php artisan config:clear
    # - composer install

