
before_script:
  - echo "Before script"
  - cd /var/www/html/easy-store #your project path
building:
  stage: build
  script:
    - echo "Build"
    # - git pull origin master
    # - composer install
    # - php artisan cache:clear
    # - php artisan config:clear
deploying:
  stage: deploy
  script:
    - echo "Deployed"
