before_script:
  - echo "Before script"
  - cd /var/www/html/easy-store
building:
  stage: build
  script:
    - echo "Build Stage"
    - whoami
    - git pull
    - composer install
    # - php artisan cache:clear
    # - php artisan config:clear

