before_script:
  - echo "Before script"
  - cd /var/www/html/easy-store
building:
  stage: build
  script:
    - echo "Build Stage"
    - whoami
    # - git reset --hard
    - git pull --ff-only
    - php artisan cache:clear
    - php artisan config:clear
    # - composer install

