before_script:
  - echo "Before script"
  - cd /var/www/html/easy-store
building:
  stage: build
  script:
    - echo "Build Stage"
    - whoami
    - git stash
    - git pull
    - composer install --no-scripts --no-interaction --prefer-source
    - php artisan migrate
    - php artisan generate:permissions
    - php artisan route:clear
    - php artisan route:cache
    - php artisan config:clear
    - php artisan config:cache
    - php artisan view:clear
    - php artisan view:cache
  only:
    - master

