before_script:
  - echo "Before script"
  - cd /var/www/html/easy-store
building:
  stage: build
  script:
    - echo "Build Stage"
    - php artisan cache:clear
    - php artisan config:clear
    - git pull origin master
    # - composer install
